@baseUrl = http://localhost:3000

### Get All Coffees
GET {{baseUrl}}/coffees

### Get all coffees with limit 10
GET {{baseUrl}}/coffees?limit=10

### Get all coffees with offset 1
GET {{baseUrl}}/coffees?offset=1

### Get all coffees with limit 10 and offset 1
GET {{baseUrl}}/coffees?limit=10&offset=1

### Get one coffee by ID
GET {{baseUrl}}/coffees/1

### Create a new coffee
POST {{baseUrl}}/coffees
Content-Type: application/json

{
  "name": "Black Gold",
  "brand": "Starbucks", 
  "flavors": ["chocolate", "caramel"]
}

### Update a coffee
PATCH {{baseUrl}}/coffees/1
Content-Type: application/json

{
  "name": "Updated Coffee Name",
  "brand": "Updated Brand",
  "flavors": ["vanilla", "hazelnut"]
}

### Delete a coffee
DELETE {{baseUrl}}/coffees/1

### Recommend a coffee -- 
### to test this, we need to enable transactions in the database first 
### without database setup, this will fail
POST {{baseUrl}}/coffees/6807f56a6942968962a86cd2/recommend
